// Aluno: Victor Gabriel Lucio | RA: A2575302

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JanelaAssistente extends javax.swing.JFrame {

    // Singleton
    private static JanelaAssistente singleJanelaAssistente;
    
    private JanelaAssistente() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public static JanelaAssistente getSingleJanelaAssistente() {
        if (singleJanelaAssistente == null) {
            singleJanelaAssistente = new JanelaAssistente();
        }
        return singleJanelaAssistente;
    }

    public void refreshComponents() {
        textProprietario.setText(Assistente.getSingleAssistente().getProprietario());
        textAssistenteVirtual.setText(Assistente.getSingleAssistente().getAssVirtual());
        textCarga.setText(String.valueOf(Assistente.getSingleAssistente().getBateria().getCarga()));
        textCapacidade.setText(String.valueOf(Assistente.getSingleAssistente().getBateria().getCapacidade()));
        textVoltagem.setText(String.valueOf(Assistente.getSingleAssistente().getBateria().getVoltagem()) + " V");
        textTemperatura.setText(String.valueOf(Assistente.getSingleAssistente().getBateria().getTemperatura()) + " Cº");
        
        // Se a carga for menor que a metade da capacidade o texto fica vermelho como alerta!
        if (
                Assistente.getSingleAssistente().getBateria().getCarga()
                <
                Assistente.getSingleAssistente().getBateria().getCapacidade() / 2
                ) {
            textCarga.setForeground(Color.RED);
        } 
        else {
            textCarga.setForeground(Color.BLACK);
        }
        
        // Se a temperatura for maior que 40 o texto fica vermelho como alerta!
        if (Assistente.getSingleAssistente().getBateria().getTemperatura() > 40) {
            textTemperatura.setForeground(Color.RED);
        } 
        else {
            textTemperatura.setForeground(Color.BLACK);
        }
     
        if (Assistente.getSingleAssistente().getSensor()) {
            textSensor.setText("Ligado");
            textSensor.setForeground(Color.GREEN);
        } else {
            textSensor.setText("Desligado");
            textSensor.setForeground(Color.RED);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInformacoes = new javax.swing.JLabel();
        separadorInformacoes = new javax.swing.JSeparator();
        labelProprietario = new javax.swing.JLabel();
        labelAssistenteVirtual = new javax.swing.JLabel();
        labelSensor = new javax.swing.JLabel();
        labelLembretes = new javax.swing.JLabel();
        separadorLembretes = new javax.swing.JSeparator();
        separadorButtons = new javax.swing.JSeparator();
        buttonSair = new javax.swing.JButton();
        textProprietario = new javax.swing.JLabel();
        textAssistenteVirtual = new javax.swing.JLabel();
        textSensor = new javax.swing.JLabel();
        labelCarga = new javax.swing.JLabel();
        textCarga = new javax.swing.JLabel();
        labelCapacidade = new javax.swing.JLabel();
        textCapacidade = new javax.swing.JLabel();
        labelVoltagem = new javax.swing.JLabel();
        textVoltagem = new javax.swing.JLabel();
        labelTemperatura = new javax.swing.JLabel();
        textTemperatura = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLembretes = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        menuEditar = new javax.swing.JMenu();
        menuEditInformacoes = new javax.swing.JMenuItem();
        menuEditLembretes = new javax.swing.JMenuItem();
        menuVizualizar = new javax.swing.JMenu();
        itemViewInformacoes = new javax.swing.JMenuItem();
        itemViewLembretes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Robô - Assistente");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        labelInformacoes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelInformacoes.setText("Informações");

        labelProprietario.setText("Proprietário:");

        labelAssistenteVirtual.setText("Assistente virtual:");

        labelSensor.setText("Sensor:");

        labelLembretes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelLembretes.setText("Lembretes");

        buttonSair.setText("Sair");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        textProprietario.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        textProprietario.setLabelFor(labelProprietario);
        textProprietario.setText("Undefined");

        textAssistenteVirtual.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        textAssistenteVirtual.setLabelFor(labelProprietario);
        textAssistenteVirtual.setText("Undefined");

        textSensor.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        textSensor.setLabelFor(labelProprietario);
        textSensor.setText("Undefined");

        labelCarga.setText("Carga:");

        textCarga.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        textCarga.setLabelFor(labelProprietario);
        textCarga.setText("Undefined");

        labelCapacidade.setText("Capacidade:");

        textCapacidade.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        textCapacidade.setLabelFor(labelProprietario);
        textCapacidade.setText("Undefined");

        labelVoltagem.setText("Voltagem:");

        textVoltagem.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        textVoltagem.setLabelFor(labelProprietario);
        textVoltagem.setText("Undefined");

        labelTemperatura.setText("Temperatura:");

        textTemperatura.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        textTemperatura.setLabelFor(labelProprietario);
        textTemperatura.setText("Undefined");

        tableLembretes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Text", "Categoria", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableLembretes);
        if (tableLembretes.getColumnModel().getColumnCount() > 0) {
            tableLembretes.getColumnModel().getColumn(0).setResizable(false);
            tableLembretes.getColumnModel().getColumn(0).setPreferredWidth(20);
            tableLembretes.getColumnModel().getColumn(3).setResizable(false);
            tableLembretes.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        menuEditar.setText("Editar");

        menuEditInformacoes.setText("Informações...");
        menuEditInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditInformacoesActionPerformed(evt);
            }
        });
        menuEditar.add(menuEditInformacoes);

        menuEditLembretes.setText("Lembretes...");
        menuEditLembretes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditLembretesActionPerformed(evt);
            }
        });
        menuEditar.add(menuEditLembretes);

        menuBar.add(menuEditar);

        menuVizualizar.setText("Visualizar");

        itemViewInformacoes.setText("Informações detalhadas...");
        itemViewInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemViewInformacoesActionPerformed(evt);
            }
        });
        menuVizualizar.add(itemViewInformacoes);

        itemViewLembretes.setText("Lembretes...");
        itemViewLembretes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemViewLembretesActionPerformed(evt);
            }
        });
        menuVizualizar.add(itemViewLembretes);

        menuBar.add(menuVizualizar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(separadorButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelInformacoes)
                                .addGap(10, 10, 10)
                                .addComponent(separadorInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelLembretes)
                                .addGap(10, 10, 10)
                                .addComponent(separadorLembretes, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelProprietario, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelAssistenteVirtual, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelSensor, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textProprietario)
                                    .addComponent(textSensor)
                                    .addComponent(textAssistenteVirtual))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCarga, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelCapacidade, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelVoltagem, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textVoltagem)
                                    .addComponent(textCapacidade)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textCarga)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelTemperatura)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textTemperatura)
                                        .addGap(20, 20, 20)))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSair)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(separadorInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInformacoes))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelProprietario)
                            .addComponent(textProprietario))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAssistenteVirtual)
                            .addComponent(textAssistenteVirtual))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSensor)
                            .addComponent(textSensor)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCarga)
                            .addComponent(textCarga)
                            .addComponent(labelTemperatura)
                            .addComponent(textTemperatura))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCapacidade)
                            .addComponent(textCapacidade))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelVoltagem)
                            .addComponent(textVoltagem))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(separadorLembretes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLembretes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(separadorButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSair)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEditInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditInformacoesActionPerformed
        JanelaAssistenteEditar.getSingleJanelaAssistenteEditar().setVisible(true);
    }//GEN-LAST:event_menuEditInformacoesActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        sair();
    }//GEN-LAST:event_buttonSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarTabela();
        refreshComponents();
    }//GEN-LAST:event_formWindowActivated

    private void itemViewInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemViewInformacoesActionPerformed
        JanelaAssistenteViewInfo.getSingleJanelaAssistenteViewInfo().setVisible(true);
    }//GEN-LAST:event_itemViewInformacoesActionPerformed

    private void itemViewLembretesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemViewLembretesActionPerformed
        JanelaAssistenteViewLembrete.getSingleJanelaAssistenteViewLembrete().setVisible(true);
    }//GEN-LAST:event_itemViewLembretesActionPerformed

    private void menuEditLembretesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditLembretesActionPerformed
        JanelaAssistenteEditarLembrete.getSingleJanelaAssistenteEditarLembrete().setVisible(true);
    }//GEN-LAST:event_menuEditLembretesActionPerformed

    private void sair() {
        int resposta =  JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saída",
                JOptionPane.YES_NO_OPTION
        );

        if(resposta == 0) {
            dispose();
        }
    }
    
    private void listarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tableLembretes.getModel();
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for (Lembrete lembrete : BDLembrete.getSingleLembreteDB().getLembretes()) {
            modelo.insertRow(posLin, new Object[]{
                lembrete.getTitulo(),
                lembrete.getTexto(),
                lembrete.getCategoria(),
                lembrete.getDate()
            });
            posLin++;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaAssistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaAssistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaAssistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaAssistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaAssistente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSair;
    private javax.swing.JMenuItem itemViewInformacoes;
    private javax.swing.JMenuItem itemViewLembretes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAssistenteVirtual;
    private javax.swing.JLabel labelCapacidade;
    private javax.swing.JLabel labelCarga;
    private javax.swing.JLabel labelInformacoes;
    private javax.swing.JLabel labelLembretes;
    private javax.swing.JLabel labelProprietario;
    private javax.swing.JLabel labelSensor;
    private javax.swing.JLabel labelTemperatura;
    private javax.swing.JLabel labelVoltagem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuEditInformacoes;
    private javax.swing.JMenuItem menuEditLembretes;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuVizualizar;
    private javax.swing.JSeparator separadorButtons;
    private javax.swing.JSeparator separadorInformacoes;
    private javax.swing.JSeparator separadorLembretes;
    private javax.swing.JTable tableLembretes;
    private javax.swing.JLabel textAssistenteVirtual;
    private javax.swing.JLabel textCapacidade;
    private javax.swing.JLabel textCarga;
    private javax.swing.JLabel textProprietario;
    private javax.swing.JLabel textSensor;
    private javax.swing.JLabel textTemperatura;
    private javax.swing.JLabel textVoltagem;
    // End of variables declaration//GEN-END:variables
}
