// Aluno: Victor Gabriel Lucio | RA: A2575302

import javax.swing.table.DefaultTableModel;

public class JanelaAssistenteEditarLembrete extends javax.swing.JFrame {

    // Singleton
    private static JanelaAssistenteEditarLembrete singleJanelaAssistenteEditarLembrete;
    
    private JanelaAssistenteEditarLembrete() {
        initComponents();
        setLocationRelativeTo(null);
    }

    // MÉTODO SINGLETON
    public static JanelaAssistenteEditarLembrete getSingleJanelaAssistenteEditarLembrete() {
        if (singleJanelaAssistenteEditarLembrete == null) {
            singleJanelaAssistenteEditarLembrete = new JanelaAssistenteEditarLembrete();
        }
        
        return singleJanelaAssistenteEditarLembrete;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonFechar = new javax.swing.JButton();
        separatorBateria1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLembretes = new javax.swing.JTable();
        labelDescricao = new javax.swing.JLabel();
        buttonAddLembrete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        buttonFechar.setText("Fechar");
        buttonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFecharActionPerformed(evt);
            }
        });

        tableLembretes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Text", "Categoria", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLembretes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLembretesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLembretes);

        labelDescricao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDescricao.setText("Clique sobre um lembrete para editar:");

        buttonAddLembrete.setText("Adicionar lembrete...");
        buttonAddLembrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddLembreteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separatorBateria1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDescricao)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(buttonAddLembrete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonFechar)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separatorBateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFechar)
                    .addComponent(buttonAddLembrete))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFecharActionPerformed
        dispose();
    }//GEN-LAST:event_buttonFecharActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarTabela();
    }//GEN-LAST:event_formWindowActivated

    private void tableLembretesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLembretesMouseClicked
        sendInformacoes();
        JanelaLembreteEdit.getSingleJanelaLembreteEdit().setVisible(true);
    }//GEN-LAST:event_tableLembretesMouseClicked

    private void buttonAddLembreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddLembreteActionPerformed
        JanelaLembreteAdd.getSingleJanelaLembreteAdd().setVisible(true);
    }//GEN-LAST:event_buttonAddLembreteActionPerformed

    private void sendInformacoes() {
        int row = tableLembretes.getSelectedRow();
        int id = Integer.parseInt(String.valueOf(tableLembretes.getValueAt(row, 0)));
        String title = String.valueOf(tableLembretes.getValueAt(row, 1));
        String content = String.valueOf(tableLembretes.getValueAt(row, 2));
        String category = String.valueOf(tableLembretes.getValueAt(row, 3));
        Object data = tableLembretes.getValueAt(row, 4);
        
        JanelaLembreteEdit.getSingleJanelaLembreteEdit().setInformacoes(
                id,
                title,
                content,
                category,
                data
        );
    }
    
    private void listarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tableLembretes.getModel();
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for (Lembrete lembrete : BDLembrete.getSingleLembreteDB().getLembretes()) {
            modelo.insertRow(posLin, new Object[]{
                lembrete.getId(),
                lembrete.getTitulo(),
                lembrete.getTexto(),
                lembrete.getCategoria(),
                lembrete.getDate()
            });
            posLin++;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaAssistenteEditarLembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaAssistenteEditarLembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaAssistenteEditarLembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaAssistenteEditarLembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaAssistenteEditarLembrete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddLembrete;
    private javax.swing.JButton buttonFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JSeparator separatorBateria1;
    private javax.swing.JTable tableLembretes;
    // End of variables declaration//GEN-END:variables
}
