// Aluno: Victor Gabriel Lucio | RA: A2575302


import javax.swing.JOptionPane;

public class JanelaArticuladoEdit extends javax.swing.JFrame {
    private int idEdit;
    
    // Singleton
    private static JanelaArticuladoEdit singleJanelaArticuladoEdit;
    
    private JanelaArticuladoEdit() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    // MÉTODO SINGLETON
    public static JanelaArticuladoEdit getSingleJanelaArticuladoEdit() {
        if (singleJanelaArticuladoEdit == null) {
            singleJanelaArticuladoEdit = new JanelaArticuladoEdit();
        }
        
        return singleJanelaArticuladoEdit;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelModelo = new javax.swing.JLabel();
        textModelo = new javax.swing.JTextField();
        labelNomeRobo = new javax.swing.JLabel();
        textNomeRobo = new javax.swing.JTextField();
        labelCorRobo = new javax.swing.JLabel();
        textCorRobo = new javax.swing.JTextField();
        separatorRobo = new javax.swing.JSeparator();
        labelTitleRobo = new javax.swing.JLabel();
        labelTitleAssistente = new javax.swing.JLabel();
        separadorAssistente = new javax.swing.JSeparator();
        labelNomeIndustria = new javax.swing.JLabel();
        textNomeIndustria = new javax.swing.JTextField();
        labelQntdEixos = new javax.swing.JLabel();
        textQntdEixos = new javax.swing.JTextField();
        textVelocidade = new javax.swing.JTextField();
        labelVelocidade = new javax.swing.JLabel();
        separadorConexao = new javax.swing.JSeparator();
        labelTitleHidraulica = new javax.swing.JLabel();
        labelPressao = new javax.swing.JLabel();
        textPressao = new javax.swing.JTextField();
        textFluxoFluido = new javax.swing.JTextField();
        labelFluxoFluido = new javax.swing.JLabel();
        labelVazao = new javax.swing.JLabel();
        textVazao = new javax.swing.JTextField();
        buttonFechar = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();
        separadorBotao = new javax.swing.JSeparator();
        comboFuncao = new javax.swing.JComboBox<>();
        labelFuncao = new javax.swing.JLabel();
        toggleCondicao = new javax.swing.JToggleButton();
        buttonRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Robô - Editar");
        setResizable(false);

        labelModelo.setText("Modelo:");

        labelNomeRobo.setText("Nome do robô:");

        labelCorRobo.setText("Cor do robô:");

        labelTitleRobo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitleRobo.setText("Robô (Geral)");

        labelTitleAssistente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitleAssistente.setText("Robô Articulado");

        labelNomeIndustria.setText("Nome da Industria:");

        labelQntdEixos.setText("Quantidade de eixos:");

        labelVelocidade.setText("Velocidade:");

        labelTitleHidraulica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitleHidraulica.setText("Conexão Hidraulica");

        labelPressao.setText("Pressão:");

        labelFluxoFluido.setText("Fluxo fluído:");

        labelVazao.setText("Vazão:");

        buttonFechar.setText("Fechar");
        buttonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFecharActionPerformed(evt);
            }
        });

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        comboFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soldagem", "Parafusamento", "Empacotamento", "Paletização" }));

        labelFuncao.setText("Função:");

        toggleCondicao.setText("Desligado");
        toggleCondicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleCondicaoActionPerformed(evt);
            }
        });

        buttonRemover.setText("Remover Robô");
        buttonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separadorBotao, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelFluxoFluido)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFluxoFluido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelPressao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textPressao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelVazao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textVazao, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelCorRobo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textCorRobo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelNomeRobo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textNomeRobo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(labelFuncao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboFuncao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelQntdEixos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textQntdEixos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelNomeIndustria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textNomeIndustria, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 1, Short.MAX_VALUE)
                                        .addComponent(labelVelocidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(toggleCondicao)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonFechar)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTitleRobo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separatorRobo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTitleAssistente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separadorAssistente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTitleHidraulica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separadorConexao))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTitleRobo)
                            .addComponent(separatorRobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelNomeRobo)
                            .addComponent(textNomeRobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelModelo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCorRobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCorRobo))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTitleAssistente)
                    .addComponent(separadorAssistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textNomeIndustria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelNomeIndustria))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelVelocidade)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textQntdEixos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelQntdEixos))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFuncao)
                    .addComponent(comboFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleCondicao))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTitleHidraulica)
                    .addComponent(separadorConexao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textPressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelPressao))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textVazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelVazao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFluxoFluido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFluxoFluido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(separadorBotao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFechar)
                    .addComponent(buttonSalvar)
                    .addComponent(buttonRemover))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFecharActionPerformed
        sair();
    }//GEN-LAST:event_buttonFecharActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        salvar();
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void toggleCondicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleCondicaoActionPerformed
        if (toggleCondicao.isSelected()) toggleCondicao.setText("Ligado");  
        else toggleCondicao.setText("Desligado");   
    }//GEN-LAST:event_toggleCondicaoActionPerformed

    private void buttonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverActionPerformed
        removerRobo();
    }//GEN-LAST:event_buttonRemoverActionPerformed

    private void sair() {
        int resposta =  JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saída",
                JOptionPane.YES_NO_OPTION
        );

        if(resposta == 0) {
            dispose();
        }
    }
    
    public void setInformacoes(Articulado articulado) {
        idEdit = articulado.getId();
        textNomeRobo.setText(articulado.getNome());
        textModelo.setText(articulado.getModelo());
        textCorRobo.setText(articulado.getCor());
        textNomeIndustria.setText(articulado.getNomeIndustria());
        textVelocidade.setText(
                String.valueOf(articulado.getVelocidade())
        );
        textQntdEixos.setText(
                String.valueOf(articulado.getQntdEixos())
        );
        textPressao.setText(
                String.valueOf(articulado.getConexao().getPressao())
        );
        textVazao.setText(
                String.valueOf(articulado.getConexao().getVazao())
        );
        
        textFluxoFluido.setText(
                String.valueOf(articulado.getConexao().getFluxoFluido())
        );
        
        
        switch (articulado.getFuncao()) {
            case "Soldagem":
                comboFuncao.setSelectedIndex(0);
                break;
                
            case "Parafusamento":
                comboFuncao.setSelectedIndex(1);
                break;
                
            case "Empacotamento":
                comboFuncao.setSelectedIndex(2);
                break;
                
            case "Paletização":
                comboFuncao.setSelectedIndex(3);
                break;
        }
    }
    
    private void salvar() {
        int resposta = JOptionPane.showConfirmDialog(
            null,
            "Tem certeza que deseja editar este Robô?",
            "Editar robô",
            JOptionPane.YES_NO_OPTION
        );

        if (resposta == 0) {
            try {
                Articulado articulado = new Articulado();
                articulado.setId(idEdit);
                articulado.setNome(textNomeRobo.getText());
                articulado.setModelo(textModelo.getText());
                articulado.setCor(textCorRobo.getText());
                articulado.setNomeIndustria(textNomeIndustria.getText());
                articulado.setQntdEixos(
                        Integer.parseInt(textQntdEixos.getText())
                );
                articulado.setVelocidade(
                        Integer.parseInt(textVelocidade.getText())
                );
                articulado.setFuncao(comboFuncao.getSelectedItem().toString());
                articulado.setCondicao(toggleCondicao.isSelected());
                articulado.getConexao().setPressao(
                        Integer.parseInt(textPressao.getText())
                );
                articulado.getConexao().setVazao(
                        Integer.parseInt(textVazao.getText())
                );
                articulado.getConexao().setFluxoFluido(
                        Integer.parseInt(textFluxoFluido.getText())
                );
                
                ArticuladoDAOImpl.getSingleArticuladoDAO().modificar(
                      articulado.getId(), articulado
                );

                JOptionPane.showMessageDialog(
                    null,
                    "Robô editado com sucesso!",
                    "Sucesso!",
                    JOptionPane.INFORMATION_MESSAGE
                );
                
                dispose();
            }
            catch (ArticuladoException | ConexaoHidraulicaException | RoboException ae) {
                JOptionPane.showMessageDialog(
                    null,
                    ae.getMessage(),
                    "ERROR!",
                    JOptionPane.ERROR_MESSAGE
                );
            }
            catch (NumberFormatException ne) {
                JOptionPane.showMessageDialog(
                        null,
                        "Cheque as entradas quem devem conter inteiros!",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE    
                );
            }
        }
    }
    
    public void removerRobo() {
        int resposta = JOptionPane.showConfirmDialog(
            null,
            "Deseja Realmente deletar o robô?",
            "DELETAR",
            JOptionPane.YES_NO_OPTION
        );
        
        if (resposta == 0) {
            ArticuladoDAOImpl.getSingleArticuladoDAO().deletar(idEdit);
            JOptionPane.showMessageDialog(
                    null,
                    "Robô deletado com sucesso!",
                    "SUCESSO!",
                    JOptionPane.INFORMATION_MESSAGE
            );
            dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaArticuladoEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaArticuladoEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaArticuladoEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaArticuladoEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaArticuladoEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFechar;
    private javax.swing.JButton buttonRemover;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JComboBox<String> comboFuncao;
    private javax.swing.JLabel labelCorRobo;
    private javax.swing.JLabel labelFluxoFluido;
    private javax.swing.JLabel labelFuncao;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelNomeIndustria;
    private javax.swing.JLabel labelNomeRobo;
    private javax.swing.JLabel labelPressao;
    private javax.swing.JLabel labelQntdEixos;
    private javax.swing.JLabel labelTitleAssistente;
    private javax.swing.JLabel labelTitleHidraulica;
    private javax.swing.JLabel labelTitleRobo;
    private javax.swing.JLabel labelVazao;
    private javax.swing.JLabel labelVelocidade;
    private javax.swing.JSeparator separadorAssistente;
    private javax.swing.JSeparator separadorBotao;
    private javax.swing.JSeparator separadorConexao;
    private javax.swing.JSeparator separatorRobo;
    private javax.swing.JTextField textCorRobo;
    private javax.swing.JTextField textFluxoFluido;
    private javax.swing.JTextField textModelo;
    private javax.swing.JTextField textNomeIndustria;
    private javax.swing.JTextField textNomeRobo;
    private javax.swing.JTextField textPressao;
    private javax.swing.JTextField textQntdEixos;
    private javax.swing.JTextField textVazao;
    private javax.swing.JTextField textVelocidade;
    private javax.swing.JToggleButton toggleCondicao;
    // End of variables declaration//GEN-END:variables
}
