// Aluno: Victor Gabriel Lucio | RA: A2575302


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JanelaArticuladoEditarRobo extends javax.swing.JFrame {

    // Singleton
    private static JanelaArticuladoEditarRobo singleJanelaArticuladoEditarRobo;
    
    private JanelaArticuladoEditarRobo() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    // MÉTODO SINGLETON
    public static JanelaArticuladoEditarRobo getSingleJanelaArticuladoEditarRobo() {
        if (singleJanelaArticuladoEditarRobo == null) {
            singleJanelaArticuladoEditarRobo = new JanelaArticuladoEditarRobo();
        }
        
        return singleJanelaArticuladoEditarRobo;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonFechar = new javax.swing.JButton();
        separador = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableArticulados = new javax.swing.JTable();
        labelDescricao = new javax.swing.JLabel();
        buttonAddRobo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Robô - Editar robôs");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        buttonFechar.setText("Fechar");
        buttonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFecharActionPerformed(evt);
            }
        });

        tableArticulados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Função", "Consumo", "Condição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableArticulados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableArticuladosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableArticulados);

        labelDescricao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDescricao.setText("Clique sobre um robô articulado para editar:");

        buttonAddRobo.setText("Adicionar Robô Articulado...");
        buttonAddRobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddRoboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separador, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDescricao)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(buttonAddRobo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonFechar)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFechar)
                    .addComponent(buttonAddRobo))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFecharActionPerformed
        dispose();
    }//GEN-LAST:event_buttonFecharActionPerformed

    private void tableArticuladosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableArticuladosMouseClicked
        sendInformacoes();
        JanelaArticuladoEdit.getSingleJanelaArticuladoEdit().setVisible(true);
    }//GEN-LAST:event_tableArticuladosMouseClicked

    private void buttonAddRoboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddRoboActionPerformed
        JanelaArticuladoAdd.getSingleJanelaArticuladoAdd().setVisible(true);
    }//GEN-LAST:event_buttonAddRoboActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarTabela();
    }//GEN-LAST:event_formWindowActivated

    private void listarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tableArticulados.getModel();
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for (Articulado articulado : BDArticulado.getSingleBDArticulado().getArticulados()) {
            modelo.insertRow(posLin, new Object[]{
                articulado.getId(),
                articulado.getNome(),
                articulado.getFuncao(),
                articulado.getConsumoEnergia(),
                articulado.getCondicao() ? "Ligado" : "Desligado"
            });
            
            posLin++;
        }
    }
    
    private void sendInformacoes() {
        int row = tableArticulados.getSelectedRow();
        int id = Integer.parseInt(String.valueOf(tableArticulados.getValueAt(row, 0)));
        
        try {
            Articulado articulado = ArticuladoDAOImpl.getSingleArticuladoDAO().get(id);
            JanelaArticuladoEdit.getSingleJanelaArticuladoEdit().setInformacoes(articulado);
        }
        catch (ArticuladoException ae) {
            JOptionPane.showMessageDialog(
                    null,
                    ae.getMessage(),
                    "ERRO!",
                    JOptionPane.ERROR_MESSAGE
            );
        }     
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaArticuladoEditarRobo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaArticuladoEditarRobo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaArticuladoEditarRobo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaArticuladoEditarRobo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaArticuladoEditarRobo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddRobo;
    private javax.swing.JButton buttonFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JSeparator separador;
    private javax.swing.JTable tableArticulados;
    // End of variables declaration//GEN-END:variables
}
